spring:
  application:
    name: async-client-docker
  activemq:
    broker-url: "tcp://activemq:61616"
    user: "admin"
    password: "secret"
    non-blocking-redelivery: true
    packages:
      trust-all: true
